title: "Lexie Midtun"
theme: minima

# Custom Navigation
header:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Resume
    url: /assets/AlexaMidtunResume.pdf
