title: "Lexie Midtun"
theme: minima

# Custom Navigation
header:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Resume
    url: /resume/

footer:
  - name: "GitHub"
    url: "https://github.com/lexiemidtun"
