title: "Lexie Midtun"
theme: minima

# You can optionally add other configurations if needed
description: "A brief description of your site."
baseurl: "" # leave this empty unless you are using a subpath
url: "https://<username>.github.io" # replace <username> with your GitHub username
